<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brands = [
            [
                'name_en' => 'Dell',
                'name_ar' => 'ديل',
                'slug' => 'dell',
                'description_en' => 'Dell Technologies is an American multinational computer technology company',
                'description_ar' => 'ديل تكنولوجيز هي شركة أمريكية متعددة الجنسيات متخصصة في تكنولوجيا الكمبيوتر',
                'logo' => 'https://logo.clearbit.com/dell.com',
                'website' => 'https://www.dell.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 1,
            ],
            [
                'name_en' => 'HP',
                'name_ar' => 'إتش بي',
                'slug' => 'hp',
                'description_en' => 'HP Inc. is an American multinational information technology company',
                'description_ar' => 'إتش بي هي شركة أمريكية متعددة الجنسيات متخصصة في تكنولوجيا المعلومات',
                'logo' => 'https://logo.clearbit.com/hp.com',
                'website' => 'https://www.hp.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 2,
            ],
            [
                'name_en' => 'Lenovo',
                'name_ar' => 'لينوفو',
                'slug' => 'lenovo',
                'description_en' => 'Lenovo Group Limited is a Chinese multinational technology company',
                'description_ar' => 'لينوفو هي شركة صينية متعددة الجنسيات متخصصة في التكنولوجيا',
                'logo' => 'https://logo.clearbit.com/lenovo.com',
                'website' => 'https://www.lenovo.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 3,
            ],
            [
                'name_en' => 'ASUS',
                'name_ar' => 'أسوس',
                'slug' => 'asus',
                'description_en' => 'ASUSTeK Computer Inc. is a Taiwanese multinational computer hardware company',
                'description_ar' => 'أسوس هي شركة تايوانية متعددة الجنسيات متخصصة في أجهزة الكمبيوتر',
                'logo' => 'https://logo.clearbit.com/asus.com',
                'website' => 'https://www.asus.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 4,
            ],
            [
                'name_en' => 'MSI',
                'name_ar' => 'إم إس آي',
                'slug' => 'msi',
                'description_en' => 'Micro-Star International is a Taiwanese multinational information technology company',
                'description_ar' => 'مايكرو ستار إنترناشونال هي شركة تايوانية متعددة الجنسيات متخصصة في تكنولوجيا المعلومات',
                'logo' => 'https://logo.clearbit.com/msi.com',
                'website' => 'https://www.msi.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 5,
            ],
            [
                'name_en' => 'Acer',
                'name_ar' => 'أيسر',
                'slug' => 'acer',
                'description_en' => 'Acer Inc. is a Taiwanese multinational hardware and electronics company',
                'description_ar' => 'أيسر هي شركة تايوانية متعددة الجنسيات متخصصة في الأجهزة والإلكترونيات',
                'logo' => 'https://logo.clearbit.com/acer.com',
                'website' => 'https://www.acer.com',
                'is_active' => true,
                'is_featured' => false,
                'order' => 6,
            ],
            [
                'name_en' => 'Apple',
                'name_ar' => 'أبل',
                'slug' => 'apple',
                'description_en' => 'Apple Inc. is an American multinational technology company',
                'description_ar' => 'أبل هي شركة أمريكية متعددة الجنسيات متخصصة في التكنولوجيا',
                'logo' => 'https://logo.clearbit.com/apple.com',
                'website' => 'https://www.apple.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 7,
            ],
            [
                'name_en' => 'Samsung',
                'name_ar' => 'سامسونج',
                'slug' => 'samsung',
                'description_en' => 'Samsung Electronics Co., Ltd. is a South Korean multinational electronics company',
                'description_ar' => 'سامسونج إلكترونيكس هي شركة كورية جنوبية متعددة الجنسيات متخصصة في الإلكترونيات',
                'logo' => 'https://logo.clearbit.com/samsung.com',
                'website' => 'https://www.samsung.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 8,
            ],
            [
                'name_en' => 'Intel',
                'name_ar' => 'إنتل',
                'slug' => 'intel',
                'description_en' => 'Intel Corporation is an American multinational corporation and technology company',
                'description_ar' => 'إنتل هي شركة أمريكية متعددة الجنسيات متخصصة في التكنولوجيا',
                'logo' => 'https://logo.clearbit.com/intel.com',
                'website' => 'https://www.intel.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 9,
            ],
            [
                'name_en' => 'AMD',
                'name_ar' => 'إي إم دي',
                'slug' => 'amd',
                'description_en' => 'Advanced Micro Devices, Inc. is an American multinational semiconductor company',
                'description_ar' => 'أدفانسد مايكرو ديفايسز هي شركة أمريكية متعددة الجنسيات متخصصة في أشباه الموصلات',
                'logo' => 'https://logo.clearbit.com/amd.com',
                'website' => 'https://www.amd.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 10,
            ],
            [
                'name_en' => 'NVIDIA',
                'name_ar' => 'إنفيديا',
                'slug' => 'nvidia',
                'description_en' => 'Nvidia Corporation is an American multinational technology company',
                'description_ar' => 'إنفيديا هي شركة أمريكية متعددة الجنسيات متخصصة في التكنولوجيا',
                'logo' => 'https://logo.clearbit.com/nvidia.com',
                'website' => 'https://www.nvidia.com',
                'is_active' => true,
                'is_featured' => true,
                'order' => 11,
            ],
            [
                'name_en' => 'Logitech',
                'name_ar' => 'لوجيتك',
                'slug' => 'logitech',
                'description_en' => 'Logitech International S.A. is a Swiss manufacturer of computer peripherals',
                'description_ar' => 'لوجيتك هي شركة سويسرية متخصصة في تصنيع ملحقات الكمبيوتر',
                'logo' => 'https://logo.clearbit.com/logitech.com',
                'website' => 'https://www.logitech.com',
                'is_active' => true,
                'is_featured' => false,
                'order' => 12,
            ],
            [
                'name_en' => 'Corsair',
                'name_ar' => 'كورسير',
                'slug' => 'corsair',
                'description_en' => 'Corsair Gaming, Inc. is an American computer peripherals and hardware company',
                'description_ar' => 'كورسير هي شركة أمريكية متخصصة في ملحقات الكمبيوتر والأجهزة',
                'logo' => 'https://logo.clearbit.com/corsair.com',
                'website' => 'https://www.corsair.com',
                'is_active' => true,
                'is_featured' => false,
                'order' => 13,
            ],
            [
                'name_en' => 'Razer',
                'name_ar' => 'رايزر',
                'slug' => 'razer',
                'description_en' => 'Razer Inc. is a Singaporean-American multinational technology company',
                'description_ar' => 'رايزر هي شركة سنغافورية أمريكية متعددة الجنسيات متخصصة في التكنولوجيا',
                'logo' => 'https://logo.clearbit.com/razer.com',
                'website' => 'https://www.razer.com',
                'is_active' => true,
                'is_featured' => false,
                'order' => 14,
            ],
        ];

        foreach ($brands as $brand) {
            Brand::create($brand);
        }
    }
}
