{{-- Explore Our Products Section - Category Carousel --}}
@if(isset($categories) && $categories->count() > 0)
    <div class="explore-products-section">
        <div class="container">
            <!-- Category Carousel -->
            <div class="category-carousel-wrapper">
                <!-- Navigation Arrow - Left -->
                <button class="carousel-nav-btn carousel-prev" onclick="slideCategoryCarousel(-1)"
                    aria-label="Previous categories">
                    <i class="fas fa-chevron-left"></i>
                </button>

                <!-- Carousel Track Container - Always LTR for proper sliding -->
                <div class="category-carousel-container" dir="ltr">
                    <div class="category-carousel-track" id="categoryCarouselTrack">
                        @foreach($categories as $category)
                            <a href="{{ route('category.show', $category->slug) }}" class="category-carousel-card">
                                <div class="category-carousel-image">
                                    @if($category->image)
                                        @if(str_starts_with($category->image, 'http'))
                                            <img src="{{ $category->image }}" alt="" loading="eager" width="124" height="124" decoding="async">
                                        @else
                                            <img src="{{ asset($category->image) }}" alt="" loading="eager" width="124" height="124" decoding="async">
                                        @endif
                                    @else
                                        <img src="https://via.placeholder.com/300x300/f3f4f6/9ca3af?text={{ urlencode($category->name) }}"
                                            alt="" loading="eager" width="124" height="124" decoding="async">
                                    @endif
                                </div>
                                <div class="category-carousel-name" dir="auto">{{ $category->name }}</div>
                            </a>
                        @endforeach
                    </div>
                </div>

                <!-- Navigation Arrow - Right -->
                <button class="carousel-nav-btn carousel-next" onclick="slideCategoryCarousel(1)"
                    aria-label="Next categories">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>

            <!-- Pagination Dots -->
            <div class="category-carousel-dots" id="categoryCarouselDots">
                <!-- Dots will be generated by JavaScript -->
            </div>
        </div>
    </div>
@else
    <!-- Empty State for Categories -->
    <div class="explore-products-section">
        <div class="container">
            <div class="empty-state-mini">
                <div class="empty-state-icon">
                    <i class="fas fa-th-large"></i>
                </div>
                <h3 class="empty-state-title">{{ __t('messages.no_categories_title') }}</h3>
                <p class="empty-state-subtitle">{{ __t('messages.no_categories_subtitle') }}</p>
                <div class="empty-state-actions">
                    <a href="{{ route('products') }}" class="empty-state-btn primary">
                        <i class="fas fa-shopping-bag"></i>
                        {{ __t('messages.view_all_products') }}
                    </a>
                </div>
            </div>
        </div>
    </div>
@endif
