
<?php if(isset($categories) && $categories->count() > 0): ?>
    <div class="explore-products-section">
        <div class="container">
            <!-- Category Carousel -->
            <div class="category-carousel-wrapper">
                <!-- Navigation Arrow - Left -->
                <button class="carousel-nav-btn carousel-prev" onclick="slideCategoryCarousel(-1)"
                    aria-label="Previous categories">
                    <i class="fas fa-chevron-left"></i>
                </button>

                <!-- Carousel Track Container - Always LTR for proper sliding -->
                <div class="category-carousel-container" dir="ltr">
                    <div class="category-carousel-track" id="categoryCarouselTrack">
                        <?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                            <a href="<?php echo e(route('category.show', $category->slug)); ?>" class="category-carousel-card">
                                <div class="category-carousel-image">
                                    <?php if($category->image): ?>
                                        <?php if(str_starts_with($category->image, 'http')): ?>
                                            <img src="<?php echo e($category->image); ?>" alt="<?php echo e($category->name); ?>" loading="lazy">
                                        <?php else: ?>
                                            <img src="<?php echo e(asset($category->image)); ?>" alt="<?php echo e($category->name); ?>" loading="lazy">
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <img src="https://via.placeholder.com/300x300/f3f4f6/9ca3af?text=<?php echo e(urlencode($category->name)); ?>"
                                            alt="<?php echo e($category->name); ?>" loading="lazy">
                                    <?php endif; ?>
                                </div>
                                <div class="category-carousel-name" dir="auto"><?php echo e($category->name); ?></div>
                            </a>
                        <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                    </div>
                </div>

                <!-- Navigation Arrow - Right -->
                <button class="carousel-nav-btn carousel-next" onclick="slideCategoryCarousel(1)"
                    aria-label="Next categories">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>

            <!-- Pagination Dots -->
            <div class="category-carousel-dots" id="categoryCarouselDots">
                <!-- Dots will be generated by JavaScript -->
            </div>
        </div>
    </div>
<?php else: ?>
    <!-- Empty State for Categories -->
    <div class="explore-products-section">
        <div class="container">
            <div class="empty-state-mini">
                <div class="empty-state-icon">
                    <i class="fas fa-th-large"></i>
                </div>
                <h3 class="empty-state-title"><?php echo e(__t('messages.no_categories_title')); ?></h3>
                <p class="empty-state-subtitle"><?php echo e(__t('messages.no_categories_subtitle')); ?></p>
                <div class="empty-state-actions">
                    <a href="<?php echo e(route('products')); ?>" class="empty-state-btn primary">
                        <i class="fas fa-shopping-bag"></i>
                        <?php echo e(__t('messages.view_all_products')); ?>

                    </a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php /**PATH C:\Users\Hamza Damra\Documents\ITCenter-Ecommerce\resources\views/home/sections/category-carousel.blade.php ENDPATH**/ ?>