<?php

namespace Database\Seeders\ProductData;

class ComponentData
{
    public static function getData(): array
    {
        return [
            [
                'name_en' => 'NVIDIA GeForce RTX 4080 Super',
                'name_ar' => 'إنفيديا جي فورس RTX 4080 سوبر',
                'name_he' => 'NVIDIA GeForce RTX 4080 Super',
                'sku' => 'NV-RTX4080S',
                'category_slug' => 'graphics-cards',
                'brand_slug' => 'nvidia',
                'short_en' => 'High-end graphics card with 16GB GDDR6X, ray tracing, DLSS 3',
                'short_ar' => 'بطاقة رسومات عالية الأداء مع 16 جيجا GDDR6X، تتبع الأشعة، DLSS 3',
                'short_he' => 'כרטיס מסך מתקדם עם 16GB GDDR6X, מעקב קרניים, DLSS 3',
                'desc_en' => 'The NVIDIA GeForce RTX 4080 Super brings Ada Lovelace architecture to enthusiast gamers. With 16GB of ultra-fast GDDR6X memory, it handles 4K gaming with ray tracing at high frame rates. DLSS 3 with Frame Generation dramatically increases performance in supported games. The third-gen RT Cores deliver stunning real-time ray-traced graphics. Perfect for creators working with 3D rendering, video editing, and AI workloads.',
                'desc_ar' => 'إنفيديا جي فورس RTX 4080 سوبر تجلب معمارية Ada Lovelace للاعبين المتحمسين. مع 16 جيجابايت من ذاكرة GDDR6X فائقة السرعة، تتعامل مع ألعاب 4K مع تتبع الأشعة بمعدلات إطارات عالية. DLSS 3 مع توليد الإطارات يزيد الأداء بشكل كبير في الألعاب المدعومة.',
                'desc_he' => 'NVIDIA GeForce RTX 4080 Super מביא את ארכיטקטורת Ada Lovelace לגיימרים נלהבים. עם 16GB של זיכרון GDDR6X מהיר במיוחד, הוא מתמודד עם משחקי 4K עם מעקב קרניים בקצבי פריימים גבוהים. DLSS 3 עם יצירת פריימים מגדיל באופן דרמטי את הביצועים במשחקים נתמכים.',
                'price' => 1199.99,
                'sale_price' => 1099.99,
                'cost' => 900.00,
                'stock' => 12,
                'warranty' => '3 Years',
                'featured' => true,
                'bestseller' => true,
                'new' => true,
                'strong_offer' => false,
                'discount' => 8,
                'image' => 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'AMD Ryzen 9 7950X Processor',
                'name_ar' => 'معالج AMD رايزن 9 7950X',
                'name_he' => 'מעבד AMD Ryzen 9 7950X',
                'sku' => 'AMD-R9-7950X',
                'category_slug' => 'processors',
                'brand_slug' => 'amd',
                'short_en' => '16-core, 32-thread processor, 5.7GHz boost, Zen 4 architecture',
                'short_ar' => 'معالج 16 نواة، 32 خيط، تعزيز 5.7 جيجاهرتز، معمارية Zen 4',
                'short_he' => 'מעבד 16 ליבות, 32 תהליכונים, הגברה ל-5.7GHz, ארכיטקטורת Zen 4',
                'desc_en' => 'The AMD Ryzen 9 7950X is the ultimate desktop processor for creators and enthusiasts. With 16 cores and 32 threads based on Zen 4 architecture, it delivers unmatched multi-threaded performance. Boost clocks up to 5.7GHz ensure excellent single-threaded performance for gaming. Built on 5nm process technology with integrated RDNA 2 graphics. Supports DDR5 memory and PCIe 5.0 for future-proof builds.',
                'desc_ar' => 'AMD Ryzen 9 7950X هو المعالج المكتبي النهائي للمبدعين والمتحمسين. مع 16 نواة و32 خيط مبنية على معمارية Zen 4، يقدم أداء متعدد الخيوط لا مثيل له. ترددات تعزيز تصل إلى 5.7 جيجاهرتز تضمن أداء ممتاز للخيط الواحد للألعاب.',
                'desc_he' => 'AMD Ryzen 9 7950X הוא מעבד השולחן האולטימטיבי ליוצרים ונלהבים. עם 16 ליבות ו-32 תהליכונים המבוססים על ארכיטקטורת Zen 4, הוא מספק ביצועים רב-תהליכיים ללא תחרות. שעוני הגברה עד 5.7GHz מבטיחים ביצועים מצוינים לתהליכון בודד למשחקים.',
                'price' => 549.99,
                'sale_price' => 499.99,
                'cost' => 400.00,
                'stock' => 35,
                'warranty' => '3 Years',
                'featured' => true,
                'bestseller' => false,
                'new' => false,
                'strong_offer' => true,
                'discount' => 9,
                'image' => 'https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Corsair Vengeance DDR5 32GB Kit',
                'name_ar' => 'كورسير فينجينس DDR5 طقم 32 جيجا',
                'name_he' => 'Corsair Vengeance DDR5 ערכת 32GB',
                'sku' => 'COR-VNG-DDR5-32',
                'category_slug' => 'ram',
                'brand_slug' => 'corsair',
                'short_en' => '32GB (2x16GB) DDR5-6000 RAM, Intel XMP 3.0, low latency',
                'short_ar' => '32 جيجا (2×16) DDR5-6000، Intel XMP 3.0، كمون منخفض',
                'short_he' => '32GB (2x16GB) DDR5-6000 RAM, Intel XMP 3.0, השהיה נמוכה',
                'desc_en' => 'Corsair Vengeance DDR5 delivers next-gen performance for DDR5 platforms. This 32GB kit (2x16GB) runs at 6000MHz with tight CL36 timings for optimal gaming and productivity performance. Intel XMP 3.0 support enables easy one-click overclocking. Onboard voltage regulation ensures stable overclocks. The compact, low-profile design ensures compatibility with large CPU coolers.',
                'desc_ar' => 'كورسير فينجينس DDR5 يقدم أداء الجيل التالي لمنصات DDR5. هذا الطقم 32 جيجابايت (2×16 جيجابايت) يعمل بسرعة 6000 ميجاهرتز مع توقيتات CL36 محكمة للألعاب والإنتاجية المثلى. دعم Intel XMP 3.0 يمكّن من كسر السرعة السهل بنقرة واحدة.',
                'desc_he' => 'Corsair Vengeance DDR5 מספק ביצועי דור הבא לפלטפורמות DDR5. ערכה זו של 32GB (2x16GB) פועלת ב-6000MHz עם תזמוני CL36 הדוקים לביצועי משחקים ופרודוקטיביות אופטימליים. תמיכה ב-Intel XMP 3.0 מאפשרת אוברקלוקינג קל בלחיצה אחת.',
                'price' => 149.99,
                'sale_price' => 129.99,
                'cost' => 95.00,
                'stock' => 50,
                'warranty' => 'Lifetime',
                'featured' => false,
                'bestseller' => true,
                'new' => false,
                'strong_offer' => false,
                'discount' => 13,
                'image' => 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1592664474505-51c549ad15c5?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Samsung 990 Pro 2TB NVMe SSD',
                'name_ar' => 'سامسونج 990 برو 2 تيرابايت NVMe SSD',
                'name_he' => 'Samsung 990 Pro 2TB NVMe SSD',
                'sku' => 'SAM-990PRO-2TB',
                'category_slug' => 'storage',
                'brand_slug' => 'samsung',
                'short_en' => '2TB PCIe 4.0 NVMe SSD, 7450MB/s read, for gaming and professionals',
                'short_ar' => '2 تيرابايت PCIe 4.0 NVMe SSD، قراءة 7450 ميجا/ثانية، للألعاب والمحترفين',
                'short_he' => '2TB PCIe 4.0 NVMe SSD, קריאה 7450MB/s, למשחקים ומקצוענים',
                'desc_en' => 'The Samsung 990 Pro pushes PCIe 4.0 to its limits with read speeds up to 7,450MB/s and write speeds up to 6,900MB/s. The 2TB capacity provides ample space for games, creative projects, and system files. Samsung\'s proprietary controller with nickel coating ensures sustained performance under heavy workloads. Optimized for PS5 with DirectStorage support for PC gaming. 5-year warranty with up to 1,200 TBW endurance.',
                'desc_ar' => 'سامسونج 990 برو يدفع PCIe 4.0 إلى حدوده مع سرعات قراءة تصل إلى 7,450 ميجابايت/ثانية وسرعات كتابة تصل إلى 6,900 ميجابايت/ثانية. سعة 2 تيرابايت توفر مساحة واسعة للألعاب والمشاريع الإبداعية وملفات النظام.',
                'desc_he' => 'Samsung 990 Pro דוחף את PCIe 4.0 לגבולותיו עם מהירויות קריאה עד 7,450MB/s ומהירויות כתיבה עד 6,900MB/s. קיבולת 2TB מספקת מקום נרחב למשחקים, פרויקטים יצירתיים וקבצי מערכת.',
                'price' => 189.99,
                'sale_price' => 169.99,
                'cost' => 130.00,
                'stock' => 40,
                'warranty' => '5 Years',
                'featured' => false,
                'bestseller' => true,
                'new' => false,
                'strong_offer' => false,
                'discount' => 11,
                'image' => 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1628557044797-f21a177c37ec?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'ASUS ROG Maximus Z790 Hero',
                'name_ar' => 'أسوس ROG ماكسيموس Z790 هيرو',
                'name_he' => 'ASUS ROG Maximus Z790 Hero',
                'sku' => 'ASUS-Z790-HERO',
                'category_slug' => 'motherboards',
                'brand_slug' => 'asus',
                'short_en' => 'Intel Z790 motherboard, DDR5, PCIe 5.0, WiFi 6E, premium VRM',
                'short_ar' => 'لوحة أم Intel Z790، DDR5، PCIe 5.0، WiFi 6E، VRM متميز',
                'short_he' => 'לוח אם Intel Z790, DDR5, PCIe 5.0, WiFi 6E, VRM פרימיום',
                'desc_en' => 'The ASUS ROG Maximus Z790 Hero is the ultimate platform for Intel 13th/14th Gen processors. Premium 20+1 power stages deliver exceptional power delivery for extreme overclocking. Dual PCIe 5.0 x16 slots and PCIe 5.0 M.2 support future-proof your build. WiFi 6E and 2.5Gb Ethernet provide blazing-fast connectivity. ROG aesthetics with customizable RGB lighting complete the enthusiast package.',
                'desc_ar' => 'ASUS ROG Maximus Z790 Hero هي المنصة النهائية لمعالجات إنتل الجيل 13/14. مراحل طاقة متميزة 20+1 توفر توصيل طاقة استثنائي لكسر السرعة الشديد. فتحات PCIe 5.0 x16 مزدوجة ودعم PCIe 5.0 M.2 تحمي بناءك للمستقبل.',
                'desc_he' => 'ASUS ROG Maximus Z790 Hero היא הפלטפורמה האולטימטיבית למעבדי Intel דור 13/14. שלבי כוח פרימיום 20+1 מספקים אספקת כוח יוצאת דופן לאוברקלוקינג קיצוני. חריצי PCIe 5.0 x16 כפולים ותמיכה ב-PCIe 5.0 M.2 מגינים על הבנייה שלך לעתיד.',
                'price' => 629.99,
                'sale_price' => 579.99,
                'cost' => 480.00,
                'stock' => 15,
                'warranty' => '3 Years',
                'featured' => true,
                'bestseller' => false,
                'new' => false,
                'strong_offer' => false,
                'discount' => 8,
                'image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1555617981-dac3880eac6e?w=800&h=600&fit=crop',
                ],
            ],
        ];
    }
}
