<?php

namespace Database\Seeders\ProductData;

class LaptopData
{
    public static function getData(): array
    {
        return [
            [
                'name_en' => 'Dell Latitude 5540 Business Laptop',
                'name_ar' => 'لابتوب ديل لاتيتيود 5540 للأعمال',
                'name_he' => 'מחשב נייד עסקי Dell Latitude 5540',
                'sku' => 'DELL-LAT-5540',
                'category_slug' => 'business-laptops',
                'brand_slug' => 'dell',
                'short_en' => 'Powerful business laptop with Intel Core i7, 16GB RAM, 512GB SSD',
                'short_ar' => 'لابتوب أعمال قوي مع معالج إنتل كور i7، ذاكرة 16 جيجا، قرص SSD 512 جيجا',
                'short_he' => 'מחשב נייד עסקי עוצמתי עם Intel Core i7, זיכרון 16GB, כונן SSD 512GB',
                'desc_en' => 'The Dell Latitude 5540 is a premium business laptop designed for professionals who demand reliability and performance. Featuring the latest 13th Gen Intel Core i7 processor, 16GB DDR5 RAM, and a fast 512GB NVMe SSD, this laptop handles demanding workloads with ease. The 15.6" Full HD display delivers crisp visuals, while the robust security features including fingerprint reader and TPM 2.0 keep your data safe. Built with a durable chassis and backed by Dell\'s enterprise support, this is the ideal choice for business professionals.',
                'desc_ar' => 'ديل لاتيتيود 5540 هو لابتوب أعمال متميز مصمم للمحترفين الذين يطلبون الموثوقية والأداء. يتميز بأحدث معالج إنتل كور i7 من الجيل الثالث عشر، وذاكرة DDR5 بسعة 16 جيجابايت، وقرص SSD NVMe سريع بسعة 512 جيجابايت، يتعامل هذا اللابتوب مع أعباء العمل المطلوبة بسهولة. شاشة 15.6 بوصة بدقة Full HD توفر صورًا واضحة، بينما ميزات الأمان القوية بما في ذلك قارئ بصمات الأصابع وTPM 2.0 تحافظ على بياناتك آمنة.',
                'desc_he' => 'Dell Latitude 5540 הוא מחשב נייד עסקי פרימיום המיועד לאנשי מקצוע הדורשים אמינות וביצועים. עם מעבד Intel Core i7 דור 13 העדכני ביותר, זיכרון DDR5 של 16GB וכונן SSD NVMe מהיר של 512GB, המחשב הנייד הזה מתמודד עם עומסי עבודה תובעניים בקלות. מסך 15.6 אינץ\' Full HD מספק תמונות חדות, בעוד תכונות האבטחה החזקות כולל קורא טביעות אצבע ו-TPM 2.0 שומרות על הנתונים שלך בטוחים.',
                'price' => 1299.99,
                'sale_price' => 1199.99,
                'cost' => 950.00,
                'stock' => 25,
                'warranty' => '3 Years',
                'featured' => true,
                'bestseller' => true,
                'new' => false,
                'strong_offer' => false,
                'discount' => 8,
                'image' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'ASUS ROG Strix G16 Gaming Laptop',
                'name_ar' => 'لابتوب أسوس روج ستريكس G16 للألعاب',
                'name_he' => 'מחשב נייד גיימינג ASUS ROG Strix G16',
                'sku' => 'ASUS-ROG-G16',
                'category_slug' => 'gaming-laptops',
                'brand_slug' => 'asus',
                'short_en' => 'Ultimate gaming laptop with RTX 4070, Intel i9, 32GB RAM, 165Hz display',
                'short_ar' => 'لابتوب ألعاب فائق مع RTX 4070، معالج i9، ذاكرة 32 جيجا، شاشة 165 هرتز',
                'short_he' => 'מחשב נייד גיימינג אולטימטיבי עם RTX 4070, Intel i9, 32GB RAM, מסך 165Hz',
                'desc_en' => 'Dominate the competition with the ASUS ROG Strix G16. Powered by Intel Core i9-13980HX and NVIDIA GeForce RTX 4070, this beast delivers exceptional gaming performance. The 16" QHD 165Hz display with G-Sync ensures smooth, tear-free visuals. With 32GB DDR5 RAM and 1TB PCIe 4.0 SSD, load times are virtually non-existent. Advanced cooling with liquid metal thermal compound keeps temperatures in check during intense gaming sessions. RGB lighting and premium audio complete the immersive experience.',
                'desc_ar' => 'سيطر على المنافسة مع أسوس روج ستريكس G16. مدعوم بمعالج إنتل كور i9-13980HX وبطاقة NVIDIA GeForce RTX 4070، هذا الوحش يقدم أداء ألعاب استثنائي. شاشة 16 بوصة QHD بتردد 165 هرتز مع G-Sync تضمن صورًا سلسة وخالية من التمزق. مع ذاكرة DDR5 بسعة 32 جيجابايت وقرص SSD PCIe 4.0 بسعة 1 تيرابايت، أوقات التحميل شبه معدومة.',
                'desc_he' => 'שלוט בתחרות עם ASUS ROG Strix G16. מונע על ידי Intel Core i9-13980HX ו-NVIDIA GeForce RTX 4070, החיה הזו מספקת ביצועי גיימינג יוצאי דופן. מסך 16 אינץ\' QHD 165Hz עם G-Sync מבטיח תמונות חלקות וללא קריעה. עם זיכרון DDR5 של 32GB וכונן SSD PCIe 4.0 של 1TB, זמני הטעינה כמעט לא קיימים.',
                'price' => 2499.99,
                'sale_price' => 2299.99,
                'cost' => 1800.00,
                'stock' => 15,
                'warranty' => '2 Years',
                'featured' => true,
                'bestseller' => false,
                'new' => true,
                'strong_offer' => true,
                'discount' => 8,
                'image' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'MacBook Pro 16" M3 Pro',
                'name_ar' => 'ماك بوك برو 16 بوصة M3 برو',
                'name_he' => 'MacBook Pro 16 אינץ\' M3 Pro',
                'sku' => 'APPLE-MBP16-M3P',
                'category_slug' => 'business-laptops',
                'brand_slug' => 'apple',
                'short_en' => 'Apple M3 Pro chip, 18GB RAM, 512GB SSD, Liquid Retina XDR display',
                'short_ar' => 'شريحة Apple M3 Pro، ذاكرة 18 جيجا، قرص 512 جيجا، شاشة Liquid Retina XDR',
                'short_he' => 'שבב Apple M3 Pro, זיכרון 18GB, כונן 512GB, מסך Liquid Retina XDR',
                'desc_en' => 'The MacBook Pro 16" with M3 Pro chip redefines professional computing. The M3 Pro delivers groundbreaking performance with a 12-core CPU and 18-core GPU, handling everything from complex code compilation to 8K video editing. The stunning 16.2" Liquid Retina XDR display with ProMotion offers 1600 nits peak brightness and P3 wide color. Up to 22 hours of battery life means you can work all day without charging. MagSafe charging, HDMI, SD card slot, and three Thunderbolt 4 ports provide versatile connectivity.',
                'desc_ar' => 'ماك بوك برو 16 بوصة مع شريحة M3 Pro يعيد تعريف الحوسبة الاحترافية. M3 Pro يقدم أداءً رائدًا مع معالج 12 نواة ومعالج رسومات 18 نواة، يتعامل مع كل شيء من تجميع الأكواد المعقدة إلى تحرير فيديو 8K. شاشة 16.2 بوصة Liquid Retina XDR المذهلة مع ProMotion توفر سطوع ذروة 1600 شمعة ولون P3 الواسع.',
                'desc_he' => 'MacBook Pro 16 אינץ\' עם שבב M3 Pro מגדיר מחדש את המחשוב המקצועי. M3 Pro מספק ביצועים פורצי דרך עם מעבד 12 ליבות ו-GPU של 18 ליבות, ומתמודד עם הכל מקומפילציית קוד מורכבת ועד עריכת וידאו 8K. מסך 16.2 אינץ\' Liquid Retina XDR המדהים עם ProMotion מציע בהירות שיא של 1600 ניטים וצבע רחב P3.',
                'price' => 2999.99,
                'sale_price' => null,
                'cost' => 2400.00,
                'stock' => 20,
                'warranty' => '1 Year AppleCare',
                'featured' => true,
                'bestseller' => true,
                'new' => true,
                'strong_offer' => false,
                'discount' => 0,
                'image' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&h=600&fit=crop',
                    'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'HP EliteBook 840 G10',
                'name_ar' => 'إتش بي إليت بوك 840 G10',
                'name_he' => 'HP EliteBook 840 G10',
                'sku' => 'HP-EB840-G10',
                'category_slug' => 'business-laptops',
                'brand_slug' => 'hp',
                'short_en' => 'Enterprise-grade laptop with Intel vPro, 16GB RAM, 256GB SSD',
                'short_ar' => 'لابتوب بمستوى المؤسسات مع Intel vPro، ذاكرة 16 جيجا، قرص 256 جيجا',
                'short_he' => 'מחשב נייד ברמת ארגון עם Intel vPro, זיכרון 16GB, כונן 256GB',
                'desc_en' => 'The HP EliteBook 840 G10 is engineered for enterprise security and manageability. With Intel vPro platform, IT administrators can remotely manage and secure devices fleet-wide. The 14" display with Sure View privacy screen prevents visual hacking. HP Wolf Security provides hardware-enforced protection against firmware attacks. The lightweight aluminum chassis weighs just 1.36kg, making it perfect for mobile professionals.',
                'desc_ar' => 'HP EliteBook 840 G10 مصمم لأمان المؤسسات وإمكانية الإدارة. مع منصة Intel vPro، يمكن لمسؤولي تكنولوجيا المعلومات إدارة وتأمين الأجهزة عن بُعد على مستوى الأسطول. شاشة 14 بوصة مع شاشة خصوصية Sure View تمنع الاختراق البصري.',
                'desc_he' => 'HP EliteBook 840 G10 מתוכנן לאבטחה וניהול ארגוני. עם פלטפורמת Intel vPro, מנהלי IT יכולים לנהל ולאבטח מכשירים מרחוק ברחבי הצי. מסך 14 אינץ\' עם מסך פרטיות Sure View מונע פריצה חזותית.',
                'price' => 1449.99,
                'sale_price' => 1349.99,
                'cost' => 1100.00,
                'stock' => 30,
                'warranty' => '3 Years',
                'featured' => false,
                'bestseller' => false,
                'new' => false,
                'strong_offer' => false,
                'discount' => 7,
                'image' => 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'name_ar' => 'لينوفو ثينك باد X1 كاربون الجيل 11',
                'name_he' => 'Lenovo ThinkPad X1 Carbon דור 11',
                'sku' => 'LEN-X1C-G11',
                'category_slug' => 'business-laptops',
                'brand_slug' => 'lenovo',
                'short_en' => 'Ultra-lightweight business laptop, Intel Core i7, 16GB RAM, 14" 2.8K OLED',
                'short_ar' => 'لابتوب أعمال خفيف الوزن، إنتل كور i7، ذاكرة 16 جيجا، شاشة OLED 2.8K',
                'short_he' => 'מחשב נייד עסקי קל במיוחד, Intel Core i7, זיכרון 16GB, מסך OLED 2.8K',
                'desc_en' => 'The legendary ThinkPad X1 Carbon continues to set the standard for business ultrabooks. At just 1.12kg, it\'s incredibly portable without compromising on features. The 14" 2.8K OLED display delivers stunning colors and deep blacks. Intel Core i7-1365U processor and 16GB LPDDR5 RAM ensure smooth multitasking. The iconic TrackPoint and precision touchpad offer multiple input options. MIL-STD-810H certified for durability.',
                'desc_ar' => 'ثينك باد X1 كاربون الأسطوري يستمر في وضع المعايير للألترابوك التجارية. بوزن 1.12 كجم فقط، إنه محمول بشكل لا يصدق دون المساومة على الميزات. شاشة OLED مقاس 14 بوصة بدقة 2.8K توفر ألوانًا مذهلة وأسود عميق.',
                'desc_he' => 'ThinkPad X1 Carbon האגדי ממשיך להציב את הסטנדרט לאולטרבוקים עסקיים. במשקל 1.12 ק"ג בלבד, הוא נייד להפליא מבלי להתפשר על תכונות. מסך OLED 14 אינץ\' 2.8K מספק צבעים מדהימים ושחורים עמוקים.',
                'price' => 1899.99,
                'sale_price' => 1749.99,
                'cost' => 1450.00,
                'stock' => 18,
                'warranty' => '3 Years',
                'featured' => true,
                'bestseller' => false,
                'new' => true,
                'strong_offer' => false,
                'discount' => 8,
                'image' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&h=600&fit=crop',
                ],
            ],
        ];
    }
}
