<?php

namespace Database\Seeders\ProductData;

class NetworkingData
{
    public static function getData(): array
    {
        return [
            [
                'name_en' => 'ASUS RT-AX86U Pro WiFi 6 Router',
                'name_ar' => 'راوتر أسوس RT-AX86U برو واي فاي 6',
                'name_he' => 'נתב ASUS RT-AX86U Pro WiFi 6',
                'sku' => 'ASUS-RTAX86U',
                'category_slug' => 'routers',
                'brand_slug' => 'asus',
                'short_en' => 'Dual-band WiFi 6 router, 5700Mbps, gaming optimization, AiMesh',
                'short_ar' => 'راوتر واي فاي 6 ثنائي النطاق، 5700 ميجابت، تحسين الألعاب، AiMesh',
                'short_he' => 'נתב WiFi 6 דו-פסי, 5700Mbps, אופטימיזציה למשחקים, AiMesh',
                'desc_en' => 'The ASUS RT-AX86U Pro is built for serious gamers and connected homes. WiFi 6 delivers speeds up to 5700Mbps with improved efficiency in crowded networks. Mobile Game Mode prioritizes gaming traffic for lower ping. 2.5G WAN port provides multi-gig internet support. AiMesh compatibility allows seamless whole-home coverage. AiProtection Pro powered by Trend Micro provides enterprise-grade security. Supports up to 128 connected devices.',
                'desc_ar' => 'ASUS RT-AX86U Pro مصمم للاعبين الجادين والمنازل المتصلة. واي فاي 6 يوفر سرعات تصل إلى 5700 ميجابت في الثانية مع كفاءة محسنة في الشبكات المزدحمة. وضع ألعاب الهاتف المحمول يعطي الأولوية لحركة الألعاب لتقليل الكمون.',
                'desc_he' => 'ASUS RT-AX86U Pro נבנה עבור גיימרים רציניים ובתים מחוברים. WiFi 6 מספק מהירויות עד 5700Mbps עם יעילות משופרת ברשתות עמוסות. Mobile Game Mode נותן עדיפות לתעבורת משחקים עבור פינג נמוך יותר.',
                'price' => 299.99,
                'sale_price' => 269.99,
                'cost' => 210.00,
                'stock' => 30,
                'warranty' => '3 Years',
                'featured' => true,
                'bestseller' => false,
                'new' => false,
                'strong_offer' => false,
                'discount' => 10,
                'image' => 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'TP-Link Deco XE75 Mesh WiFi 6E System',
                'name_ar' => 'نظام شبكة TP-Link Deco XE75 واي فاي 6E',
                'name_he' => 'מערכת רשת TP-Link Deco XE75 WiFi 6E',
                'sku' => 'TPL-DECOXE75',
                'category_slug' => 'access-points',
                'brand_slug' => 'tp-link',
                'short_en' => '3-pack WiFi 6E mesh system, 5400Mbps, covers up to 7200 sq ft',
                'short_ar' => 'نظام شبكة واي فاي 6E من 3 قطع، 5400 ميجابت، يغطي حتى 670 متر مربع',
                'short_he' => 'מערכת רשת WiFi 6E של 3 יחידות, 5400Mbps, מכסה עד 670 מ"ר',
                'desc_en' => 'The TP-Link Deco XE75 brings WiFi 6E to your entire home. The 3-pack covers up to 7,200 square feet with seamless roaming. The new 6GHz band provides a dedicated backhaul for maximum performance. AI-Driven Mesh optimizes your network in real-time. Easy setup with the Deco app takes just minutes. TP-Link HomeShield provides comprehensive security including real-time IoT protection. Supports up to 200 devices.',
                'desc_ar' => 'TP-Link Deco XE75 يجلب واي فاي 6E إلى منزلك بالكامل. حزمة من 3 قطع تغطي حتى 670 متر مربع مع تجوال سلس. نطاق 6 جيجاهرتز الجديد يوفر رابطًا خلفيًا مخصصًا للأداء الأقصى.',
                'desc_he' => 'TP-Link Deco XE75 מביא WiFi 6E לכל הבית שלך. חבילת 3 יחידות מכסה עד 670 מ"ר עם נדידה חלקה. פס 6GHz החדש מספק ערוץ אחורי ייעודי לביצועים מקסימליים.',
                'price' => 379.99,
                'sale_price' => 329.99,
                'cost' => 260.00,
                'stock' => 20,
                'warranty' => '2 Years',
                'featured' => false,
                'bestseller' => true,
                'new' => true,
                'strong_offer' => false,
                'discount' => 13,
                'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Ubiquiti UniFi Switch 24 PoE',
                'name_ar' => 'سويتش يوبيكويتي يوني فاي 24 منفذ PoE',
                'name_he' => 'מתג Ubiquiti UniFi Switch 24 PoE',
                'sku' => 'UBQ-USW24POE',
                'category_slug' => 'switches',
                'brand_slug' => 'ubiquiti',
                'short_en' => '24-port managed PoE+ switch, 95W budget, rack-mountable',
                'short_ar' => 'سويتش مُدار 24 منفذ PoE+، ميزانية 95 واط، قابل للتركيب في الراك',
                'short_he' => 'מתג מנוהל 24 פורטים PoE+, תקציב 95W, להרכבה בארון תקשורת',
                'desc_en' => 'The Ubiquiti UniFi Switch 24 PoE brings enterprise-grade switching to small businesses and prosumers. 24 Gigabit Ethernet ports with 16 PoE+ ports provide 95W total PoE budget. Two 1G SFP ports enable fiber uplinks. Managed through the intuitive UniFi Controller software for centralized network management. Near-silent fanless design suits office environments. Layer 2 features include VLANs, port isolation, and storm control.',
                'desc_ar' => 'Ubiquiti UniFi Switch 24 PoE يجلب التبديل بمستوى المؤسسات للشركات الصغيرة والمستخدمين المحترفين. 24 منفذ جيجابت إيثرنت مع 16 منفذ PoE+ توفر ميزانية PoE إجمالية 95 واط. منفذان 1G SFP يمكّنان وصلات الألياف.',
                'desc_he' => 'Ubiquiti UniFi Switch 24 PoE מביא מיתוג ברמת ארגון לעסקים קטנים ופרוסיומרים. 24 פורטי Gigabit Ethernet עם 16 פורטי PoE+ מספקים תקציב PoE כולל של 95W. שני פורטי 1G SFP מאפשרים קישורי סיבים.',
                'price' => 379.99,
                'sale_price' => 349.99,
                'cost' => 280.00,
                'stock' => 15,
                'warranty' => '2 Years',
                'featured' => false,
                'bestseller' => false,
                'new' => false,
                'strong_offer' => false,
                'discount' => 8,
                'image' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Netgear Nighthawk AX12 WiFi 6 Router',
                'name_ar' => 'راوتر نتجير نايت هوك AX12 واي فاي 6',
                'name_he' => 'נתב Netgear Nighthawk AX12 WiFi 6',
                'sku' => 'NG-RAXE500',
                'category_slug' => 'routers',
                'brand_slug' => 'netgear',
                'short_en' => 'Tri-band WiFi 6E router, 10.8Gbps, 12-stream, 2.5G multi-gig',
                'short_ar' => 'راوتر واي فاي 6E ثلاثي النطاق، 10.8 جيجابت، 12 تيار، متعدد الجيجا 2.5G',
                'short_he' => 'נתב WiFi 6E תלת-פסי, 10.8Gbps, 12 זרמים, מולטי-גיג 2.5G',
                'desc_en' => 'The Netgear Nighthawk AX12 delivers blazing-fast WiFi 6E with tri-band technology. Combined speeds up to 10.8Gbps across 2.4GHz, 5GHz, and 6GHz bands. 12 simultaneous streams ensure every device gets bandwidth. 2.5G Ethernet port supports multi-gig internet plans. Powerful 1.8GHz quad-core processor handles heavy traffic. NETGEAR Armor provides advanced cyber security. Ideal for 4K/8K streaming, VR gaming, and smart homes.',
                'desc_ar' => 'Netgear Nighthawk AX12 يقدم واي فاي 6E فائق السرعة مع تقنية ثلاثية النطاق. سرعات مجمعة تصل إلى 10.8 جيجابت في الثانية عبر نطاقات 2.4 و5 و6 جيجاهرتز. 12 تيارًا متزامنًا يضمن حصول كل جهاز على عرض النطاق.',
                'desc_he' => 'Netgear Nighthawk AX12 מספק WiFi 6E מהיר בזק עם טכנולוגיה תלת-פסית. מהירויות משולבות עד 10.8Gbps על פסי 2.4GHz, 5GHz ו-6GHz. 12 זרמים בו-זמניים מבטיחים שכל מכשיר מקבל רוחב פס.',
                'price' => 599.99,
                'sale_price' => 549.99,
                'cost' => 420.00,
                'stock' => 10,
                'warranty' => '2 Years',
                'featured' => true,
                'bestseller' => false,
                'new' => true,
                'strong_offer' => true,
                'discount' => 8,
                'image' => 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'CAT6A Ethernet Cable 50ft Blue',
                'name_ar' => 'كابل إيثرنت CAT6A 15 متر أزرق',
                'name_he' => 'כבל Ethernet CAT6A 15 מטר כחול',
                'sku' => 'CBL-CAT6A-50',
                'category_slug' => 'networking',
                'brand_slug' => 'generic',
                'short_en' => '50ft CAT6A shielded cable, 10Gbps, gold-plated connectors',
                'short_ar' => 'كابل CAT6A محمي 15 متر، 10 جيجابت، موصلات مطلية بالذهب',
                'short_he' => 'כבל CAT6A מוגן 15 מטר, 10Gbps, מחברים מצופים זהב',
                'desc_en' => 'This professional-grade CAT6A Ethernet cable delivers reliable 10 Gigabit speeds over 50 feet. Shielded twisted pair (STP) construction minimizes electromagnetic interference. Gold-plated RJ45 connectors ensure a solid connection with corrosion resistance. Snagless boot design protects the clip during installation. Perfect for connecting gaming consoles, PCs, smart TVs, and network equipment to your router or switch.',
                'desc_ar' => 'كابل إيثرنت CAT6A الاحترافي يوفر سرعات 10 جيجابت موثوقة على مسافة 15 متر. بناء الزوج الملتوي المحمي (STP) يقلل التداخل الكهرومغناطيسي. موصلات RJ45 المطلية بالذهب تضمن اتصالًا قويًا مع مقاومة التآكل.',
                'desc_he' => 'כבל Ethernet CAT6A מקצועי זה מספק מהירויות 10 Gigabit אמינות על פני 15 מטר. בניית Shielded Twisted Pair (STP) ממזערת הפרעות אלקטרומגנטיות. מחברי RJ45 מצופי זהב מבטיחים חיבור יציב עם עמידות בפני קורוזיה.',
                'price' => 24.99,
                'sale_price' => 19.99,
                'cost' => 12.00,
                'stock' => 100,
                'warranty' => 'Lifetime',
                'featured' => false,
                'bestseller' => true,
                'new' => false,
                'strong_offer' => false,
                'discount' => 20,
                'image' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop',
                ],
            ],
        ];
    }
}
