<?php

namespace Database\Seeders\ProductData;

class PeripheralData
{
    public static function getData(): array
    {
        return [
            [
                'name_en' => 'Logitech MX Master 3S Wireless Mouse',
                'name_ar' => 'ماوس لوجيتك MX ماستر 3S لاسلكي',
                'name_he' => 'עכבר אלחוטי Logitech MX Master 3S',
                'sku' => 'LOG-MXM3S',
                'category_slug' => 'mice',
                'brand_slug' => 'logitech',
                'short_en' => 'Premium wireless mouse with 8K DPI sensor, quiet clicks, USB-C',
                'short_ar' => 'ماوس لاسلكي متميز مع مستشعر 8K DPI، نقرات هادئة، USB-C',
                'short_he' => 'עכבר אלחוטי פרימיום עם חיישן 8K DPI, לחיצות שקטות, USB-C',
                'desc_en' => 'The Logitech MX Master 3S is the pinnacle of productivity mice. The 8,000 DPI Darkfield sensor tracks on virtually any surface including glass. Quiet Click technology reduces click noise by 90% while maintaining satisfying tactile feedback. MagSpeed electromagnetic scroll wheel scrolls 1,000 lines per second. Connect to up to 3 devices via Bluetooth or the included Logi Bolt receiver. 70-day battery life with USB-C quick charging.',
                'desc_ar' => 'لوجيتك MX ماستر 3S هو قمة ماوسات الإنتاجية. مستشعر Darkfield بدقة 8,000 DPI يتتبع على أي سطح تقريبًا بما في ذلك الزجاج. تقنية النقر الهادئ تقلل ضوضاء النقر بنسبة 90% مع الحفاظ على ردود فعل لمسية مرضية.',
                'desc_he' => 'Logitech MX Master 3S הוא פסגת עכברי הפרודוקטיביות. חיישן Darkfield של 8,000 DPI עוקב על כמעט כל משטח כולל זכוכית. טכנולוגיית לחיצה שקטה מפחיתה רעש לחיצה ב-90% תוך שמירה על משוב מגע משביע רצון.',
                'price' => 99.99,
                'sale_price' => 89.99,
                'cost' => 65.00,
                'stock' => 60,
                'warranty' => '2 Years',
                'featured' => true,
                'bestseller' => true,
                'new' => false,
                'strong_offer' => false,
                'discount' => 10,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Razer BlackWidow V4 Pro Mechanical Keyboard',
                'name_ar' => 'لوحة مفاتيح ريزر بلاك ويدو V4 برو ميكانيكية',
                'name_he' => 'מקלדת מכנית Razer BlackWidow V4 Pro',
                'sku' => 'RAZ-BWV4PRO',
                'category_slug' => 'keyboards',
                'brand_slug' => 'razer',
                'short_en' => 'Mechanical gaming keyboard with Razer Green switches, RGB, media keys',
                'short_ar' => 'لوحة مفاتيح ألعاب ميكانيكية مع مفاتيح Razer Green، RGB، مفاتيح وسائط',
                'short_he' => 'מקלדת גיימינג מכנית עם מתגי Razer Green, RGB, מקשי מדיה',
                'desc_en' => 'The Razer BlackWidow V4 Pro is the ultimate gaming keyboard for competitive players. Razer Green Mechanical Switches deliver tactile, clicky feedback with 50g actuation force. Per-key RGB lighting with Razer Chroma supports 16.8 million colors and syncs with games. Dedicated media keys and multi-function roller provide quick access to volume and playback. Magnetic wrist rest and durable doubleshot ABS keycaps complete the premium package.',
                'desc_ar' => 'ريزر بلاك ويدو V4 برو هي لوحة المفاتيح النهائية للاعبين التنافسيين. مفاتيح Razer Green الميكانيكية توفر ردود فعل لمسية ونقرية مع قوة تشغيل 50 جرام. إضاءة RGB لكل مفتاح مع Razer Chroma تدعم 16.8 مليون لون وتتزامن مع الألعاب.',
                'desc_he' => 'Razer BlackWidow V4 Pro היא מקלדת הגיימינג האולטימטיבית לשחקנים תחרותיים. מתגים מכניים Razer Green מספקים משוב מגע ולחיצה עם כוח הפעלה של 50 גרם. תאורת RGB לכל מקש עם Razer Chroma תומכת ב-16.8 מיליון צבעים ומסתנכרנת עם משחקים.',
                'price' => 229.99,
                'sale_price' => 199.99,
                'cost' => 150.00,
                'stock' => 25,
                'warranty' => '2 Years',
                'featured' => false,
                'bestseller' => false,
                'new' => true,
                'strong_offer' => false,
                'discount' => 13,
                'image' => 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Samsung Odyssey G9 49" Curved Monitor',
                'name_ar' => 'شاشة سامسونج أوديسي G9 49 بوصة منحنية',
                'name_he' => 'מסך קעור Samsung Odyssey G9 49 אינץ\'',
                'sku' => 'SAM-G9-49',
                'category_slug' => 'monitors',
                'brand_slug' => 'samsung',
                'short_en' => '49" DQHD curved gaming monitor, 240Hz, 1ms, HDR1000, QLED',
                'short_ar' => 'شاشة ألعاب منحنية 49 بوصة DQHD، 240 هرتز، 1 مللي ثانية، HDR1000، QLED',
                'short_he' => 'מסך גיימינג קעור 49 אינץ\' DQHD, 240Hz, 1ms, HDR1000, QLED',
                'desc_en' => 'The Samsung Odyssey G9 is the ultimate immersive gaming display. The massive 49" 1000R curved panel wraps around your field of vision with 5120x1440 DQHD resolution. 240Hz refresh rate and 1ms response time deliver buttery-smooth gameplay. QLED technology with HDR1000 produces stunning colors and contrast. G-Sync and FreeSync Premium Pro ensure tear-free gaming. Replace your dual monitor setup with one epic display.',
                'desc_ar' => 'سامسونج أوديسي G9 هي شاشة الألعاب الغامرة النهائية. لوحة منحنية ضخمة 49 بوصة 1000R تلتف حول مجال رؤيتك بدقة 5120×1440 DQHD. معدل تحديث 240 هرتز ووقت استجابة 1 مللي ثانية يوفران تجربة لعب سلسة.',
                'desc_he' => 'Samsung Odyssey G9 הוא מסך הגיימינג האולטימטיבי לחוויה סוחפת. הפאנל הקעור העצום של 49 אינץ\' 1000R עוטף את שדה הראייה שלך ברזולוציית 5120x1440 DQHD. קצב רענון 240Hz וזמן תגובה 1ms מספקים משחק חלק כמו חמאה.',
                'price' => 1299.99,
                'sale_price' => 1099.99,
                'cost' => 850.00,
                'stock' => 8,
                'warranty' => '3 Years',
                'featured' => true,
                'bestseller' => false,
                'new' => false,
                'strong_offer' => true,
                'discount' => 15,
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Sony WH-1000XM5 Wireless Headphones',
                'name_ar' => 'سماعات سوني WH-1000XM5 لاسلكية',
                'name_he' => 'אוזניות אלחוטיות Sony WH-1000XM5',
                'sku' => 'SONY-WH1000XM5',
                'category_slug' => 'headsets',
                'brand_slug' => 'sony',
                'short_en' => 'Premium noise-canceling headphones, 30hr battery, Hi-Res Audio',
                'short_ar' => 'سماعات متميزة بإلغاء الضوضاء، بطارية 30 ساعة، صوت عالي الدقة',
                'short_he' => 'אוזניות פרימיום עם ביטול רעשים, סוללה 30 שעות, Hi-Res Audio',
                'desc_en' => 'The Sony WH-1000XM5 sets the industry standard for wireless noise-canceling headphones. Eight microphones and two processors deliver the most advanced noise cancellation yet. 30mm carbon fiber drivers produce crystal-clear Hi-Res Audio. Multipoint connection lets you switch between two devices seamlessly. 30-hour battery life with quick charging (3-hour playback from 3-minute charge). Speak-to-Chat automatically pauses music when you talk.',
                'desc_ar' => 'سوني WH-1000XM5 تضع معيار الصناعة للسماعات اللاسلكية بإلغاء الضوضاء. ثمانية ميكروفونات ومعالجان يقدمان أكثر إلغاء ضوضاء تقدمًا حتى الآن. مشغلات من ألياف الكربون 30 مم تنتج صوتًا عالي الدقة واضحًا.',
                'desc_he' => 'Sony WH-1000XM5 מציב את תקן התעשייה לאוזניות אלחוטיות עם ביטול רעשים. שמונה מיקרופונים ושני מעבדים מספקים את ביטול הרעשים המתקדם ביותר עד כה. דרייברים מסיבי פחמן 30 מ"מ מייצרים Hi-Res Audio צלול כבדולח.',
                'price' => 399.99,
                'sale_price' => 349.99,
                'cost' => 280.00,
                'stock' => 45,
                'warranty' => '1 Year',
                'featured' => true,
                'bestseller' => true,
                'new' => false,
                'strong_offer' => false,
                'discount' => 13,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&h=600&fit=crop',
                ],
            ],
            [
                'name_en' => 'Logitech C920 HD Pro Webcam',
                'name_ar' => 'كاميرا ويب لوجيتك C920 HD برو',
                'name_he' => 'מצלמת רשת Logitech C920 HD Pro',
                'sku' => 'LOG-C920',
                'category_slug' => 'webcams',
                'brand_slug' => 'logitech',
                'short_en' => '1080p HD webcam with stereo microphones, autofocus, light correction',
                'short_ar' => 'كاميرا ويب 1080p HD مع ميكروفونات ستيريو، تركيز تلقائي، تصحيح الإضاءة',
                'short_he' => 'מצלמת רשת 1080p HD עם מיקרופונים סטריאו, פוקוס אוטומטי, תיקון תאורה',
                'desc_en' => 'The Logitech C920 HD Pro is the go-to webcam for video calls and streaming. Full HD 1080p at 30fps delivers sharp, detailed video. Dual stereo microphones capture clear audio without additional equipment. HD autofocus keeps you sharp even when moving. Automatic light correction adapts to any lighting condition. Compatible with all major video conferencing platforms. Includes tripod-ready universal clip.',
                'desc_ar' => 'لوجيتك C920 HD برو هي كاميرا الويب المفضلة لمكالمات الفيديو والبث. Full HD 1080p بمعدل 30 إطارًا في الثانية توفر فيديو حادًا ومفصلًا. ميكروفونات ستيريو مزدوجة تلتقط صوتًا واضحًا دون معدات إضافية.',
                'desc_he' => 'Logitech C920 HD Pro היא מצלמת הרשת המועדפת לשיחות וידאו וסטרימינג. Full HD 1080p ב-30fps מספק וידאו חד ומפורט. מיקרופונים סטריאו כפולים לוכדים אודיו ברור ללא ציוד נוסף.',
                'price' => 79.99,
                'sale_price' => 69.99,
                'cost' => 50.00,
                'stock' => 70,
                'warranty' => '2 Years',
                'featured' => false,
                'bestseller' => true,
                'new' => false,
                'strong_offer' => false,
                'discount' => 13,
                'image' => 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=800&h=600&fit=crop',
                'gallery' => [
                    'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=600&fit=crop',
                ],
            ],
        ];
    }
}
